// project/src/App.tsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { Toaster } from 'react-hot-toast';
import { useAuth } from './hooks/useAuth';

import Layout from './components/Layout/Layout';
import ProtectedRoute from './components/ProtectedRoute/ProtectedRoute';
import Login from './pages/Login/Login';
import Main from './pages/Main/Main';
import Expedientes from './pages/Expedientes/Expedientes';
import ExpedienteDetail from './pages/ExpedienteDetail/ExpedienteDetail';
import RegistrarUsuario from './pages/RegistrarUsuario/RegistrarUsuario';

function App() {
  const { isAuthenticated, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-pulse text-gray-500">Cargando aplicación...</div>
      </div>
    );
  }

  return (
    <Router>
      <div className="App">
        <Routes>
          <Route 
            path="/login" 
            element={
              isAuthenticated ? <Navigate to="/main" replace /> : <Login />
            } 
          />
          
          <Route 
            path="/" 
            element={
              <ProtectedRoute>
                <Layout />
              </ProtectedRoute>
            }
          >
            <Route index element={<Navigate to="/main" replace />} />
            <Route path="main" element={<Main />} />
            <Route path="expedientes" element={<Expedientes />} />
            <Route path="expedientes/:id" element={<ExpedienteDetail />} />
            <Route path="usuarios/registrar" element={<RegistrarUsuario />} />
          </Route>
          
          <Route path="*" element={<Navigate to="/main" replace />} />
        </Routes>
        
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#363636',
              color: '#fff',
            },
            success: {
              iconTheme: {
                primary: '#4ade80',
                secondary: '#fff',
              },
            },
            error: {
              iconTheme: {
                primary: '#ef4444',
                secondary: '#fff',
              },
            },
          }}
        />
      </div>
    </Router>
  );
}

export default App;

// backend-laravel/resources/js/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import ToastContainer from '@/components/ToastContainer.vue';
import { useAuth } from '@/composables/useAuth';

const { isLoading } = useAuth();
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <div
      v-if="isLoading"
      class="flex min-h-screen items-center justify-center"
      role="status"
      aria-live="polite"
    >
      <span class="animate-pulse text-gray-500">Cargando aplicación...</span>
    </div>

    <RouterView v-else />
    <ToastContainer />
  </div>
</template>
