// backend-laravel/resources/js/components/FileUploader/FileUploader.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { AlertCircle, File as FileIcon, Upload, X } from '@lucide/vue';
import Button from '@/components/UI/Button.vue';
import ProgressBar from '@/components/UI/ProgressBar.vue';
import { useToast } from '@/composables/useToast';

interface FileUploaderProps {
    onUpload: (file: File, onProgress?: (progress: number) => void) => Promise<void>;
    accept?: string;
    maxSize?: number;
    loading?: boolean;
    multiple?: boolean;
}

const props = defineProps<FileUploaderProps>();
const toast = useToast();

const accept = computed(() => props.accept ?? '.pdf,.doc,.docx');
const maxSize = computed(
    () => props.maxSize ?? Number.parseInt(import.meta.env.VITE_MAX_FILE_SIZE || '10485760', 10),
);
const loading = computed(() => props.loading ?? false);
const multiple = computed(() => props.multiple ?? false);

const dragOver = ref(false);
const selectedFiles = ref<File[]>([]);
const uploadProgress = ref(0);
const isUploading = ref(false);

const formatFileSize = (bytes: number): string => {
    if (bytes === 0) {
        return '0 Bytes';
    }

    const unit = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const index = Math.floor(Math.log(bytes) / Math.log(unit));

    return `${Math.round((bytes / Math.pow(unit, index)) * 100) / 100} ${sizes[index]}`;
};

const validateFileType = (file: File, acceptedTypes: string[]): boolean => {
    const fileExtension = `.${file.name.split('.').pop()?.toLowerCase()}`;
    const fileMimeType = file.type.toLowerCase();

    return acceptedTypes.some((type) => {
        const normalizedType = type.trim().toLowerCase();

        if (normalizedType.startsWith('.')) {
            return fileExtension === normalizedType;
        }

        if (normalizedType.includes('/')) {
            return (
                fileMimeType === normalizedType ||
                fileMimeType.startsWith(normalizedType.replace('*', ''))
            );
        }

        return false;
    });
};

const validateFile = (file: File): boolean => {
    if (file.size > maxSize.value) {
        toast.error(`El archivo es demasiado grande. Máximo ${formatFileSize(maxSize.value)}`);
        return false;
    }

    const acceptedTypes = accept.value.split(',').map((type) => type.trim());
    if (!validateFileType(file, acceptedTypes)) {
        toast.error(`Tipo de archivo no permitido. Tipos aceptados: ${accept.value}`);
        return false;
    }

    return true;
};

const handleFileSelect = (files: FileList | null): void => {
    if (!files) {
        return;
    }

    const validFiles = Array.from(files).filter(validateFile);
    selectedFiles.value = multiple.value
        ? [...selectedFiles.value, ...validFiles]
        : validFiles.slice(0, 1);
};

const handleDrop = (event: DragEvent): void => {
    dragOver.value = false;
    handleFileSelect(event.dataTransfer?.files ?? null);
};

const handleFileChange = (event: Event): void => {
    const input = event.target as HTMLInputElement;
    handleFileSelect(input.files);
    input.value = '';
};

const handleUpload = async (file: File): Promise<void> => {
    isUploading.value = true;
    uploadProgress.value = 0;

    try {
        await props.onUpload(file, (progress) => {
            uploadProgress.value = progress;
        });

        selectedFiles.value = selectedFiles.value.filter((selectedFile) => selectedFile !== file);
    } catch {
        // El contenedor conoce el recurso y muestra el mensaje de error apropiado.
    } finally {
        isUploading.value = false;
        uploadProgress.value = 0;
    }
};

const removeFile = (file: File): void => {
    selectedFiles.value = selectedFiles.value.filter((selectedFile) => selectedFile !== file);
};

const clearAllFiles = (): void => {
    selectedFiles.value = [];
};
</script>

<template>
    <div class="space-y-4">
        <div
            v-if="selectedFiles.length === 0"
            class="rounded-lg border-2 border-dashed p-8 text-center transition-colors"
            :class="dragOver ? 'border-blue-400 bg-blue-50' : 'border-gray-300 hover:border-gray-400'"
            @dragover.prevent="dragOver = true"
            @dragleave="dragOver = false"
            @drop.prevent="handleDrop"
        >
            <Upload class="mx-auto mb-4 h-12 w-12 text-gray-400" />
            <p class="mb-2 text-sm text-gray-600">
                Arrastra y suelta {{ multiple ? 'archivos' : 'un archivo' }} aquí, o
            </p>
            <label class="inline-block">
                <input
                    type="file"
                    class="hidden"
                    :accept="accept"
                    :multiple="multiple"
                    :disabled="loading || isUploading"
                    @change="handleFileChange"
                />
                <Button
                    variant="outline"
                    as="span"
                    class="cursor-pointer"
                    :disabled="loading || isUploading"
                >
                    Seleccionar {{ multiple ? 'archivos' : 'archivo' }}
                </Button>
            </label>
            <p class="mt-2 text-xs text-gray-500">
                Tipos permitidos: {{ accept }} • Máximo {{ formatFileSize(maxSize) }}<template v-if="multiple">
                    por archivo</template
                >
            </p>
        </div>

        <div v-else class="space-y-3">
            <div class="flex items-center justify-between">
                <h4 class="text-sm font-medium text-gray-900">
                    {{ selectedFiles.length }} archivo{{ selectedFiles.length > 1 ? 's' : '' }} seleccionado{{
                        selectedFiles.length > 1 ? 's' : ''
                    }}
                </h4>
                <Button
                    v-if="selectedFiles.length > 1"
                    variant="outline"
                    size="sm"
                    :disabled="isUploading"
                    @click="clearAllFiles"
                >
                    Limpiar todo
                </Button>
            </div>

            <ProgressBar v-if="isUploading" :progress="uploadProgress" />

            <div class="space-y-2">
                <div
                    v-for="(file, index) in selectedFiles"
                    :key="`${file.name}-${file.lastModified}-${index}`"
                    class="rounded-lg border border-gray-200 p-4"
                >
                    <div class="flex items-center justify-between">
                        <div class="flex items-center space-x-3">
                            <FileIcon class="h-8 w-8 text-blue-600" />
                            <div>
                                <p class="text-sm font-medium text-gray-900">{{ file.name }}</p>
                                <p class="text-sm text-gray-500">{{ formatFileSize(file.size) }}</p>
                            </div>
                        </div>
                        <div class="flex items-center space-x-2">
                            <Button
                                variant="primary"
                                size="sm"
                                :loading="isUploading"
                                :disabled="loading"
                                @click="handleUpload(file)"
                            >
                                Subir
                            </Button>
                            <button
                                type="button"
                                class="text-gray-400 transition-colors hover:text-red-600"
                                :disabled="isUploading || loading"
                                :aria-label="`Quitar ${file.name}`"
                                @click="removeFile(file)"
                            >
                                <X class="h-5 w-5" />
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="rounded-lg border-2 border-dashed border-gray-300 p-4 text-center">
                <label class="cursor-pointer">
                    <input
                        type="file"
                        class="hidden"
                        :accept="accept"
                        :multiple="multiple"
                        :disabled="loading || isUploading"
                        @change="handleFileChange"
                    />
                    <span class="text-sm text-gray-600">+ Agregar más archivos</span>
                </label>
            </div>
        </div>

        <div class="text-xs text-gray-500">
            <div class="flex items-center space-x-1">
                <AlertCircle class="h-3 w-3" />
                <span>Los archivos se suben individualmente. Tipos permitidos: {{ accept }}</span>
            </div>
        </div>
    </div>
</template>

// project/src/components/FileUploader/FileUploader.tsx
import React, { useState } from 'react';
import { Upload, File, X, AlertCircle } from 'lucide-react';
import Button from '../UI/Button';
import ProgressBar from '../UI/ProgressBar';
import { validateFileSize, validateFileType, formatFileSize } from '../../utils/fileDownload';
import toast from 'react-hot-toast';

interface FileUploaderProps {
  onUpload: (file: File, onProgress?: (progress: number) => void) => Promise<void>;
  accept?: string;
  maxSize?: number;
  loading?: boolean;
  multiple?: boolean;
}

const FileUploader: React.FC<FileUploaderProps> = ({
  onUpload,
  accept = '.docx',
  maxSize = parseInt(import.meta.env.VITE_MAX_FILE_SIZE || '10485760'), // 10MB default
  loading = false,
  multiple = false,
}) => {
  const [dragOver, setDragOver] = useState(false);
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [isUploading, setIsUploading] = useState(false);

  const validateFile = (file: File) => {
    if (!validateFileSize(file, maxSize)) {
      toast.error(`El archivo es demasiado grande. Máximo ${formatFileSize(maxSize)}`);
      return false;
    }

    const acceptedTypes = accept.split(',').map(type => type.trim());
    if (!validateFileType(file, acceptedTypes)) {
      toast.error(`Tipo de archivo no permitido. Tipos aceptados: ${accept}`);
      return false;
    }

    return true;
  };

  const handleFileSelect = (files: FileList | null) => {
    if (!files) return;

    const validFiles: File[] = [];
    Array.from(files).forEach(file => {
      if (validateFile(file)) {
        validFiles.push(file);
      }
    });

    if (multiple) {
      setSelectedFiles(prev => [...prev, ...validFiles]);
    } else {
      setSelectedFiles(validFiles.slice(0, 1));
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    handleFileSelect(e.dataTransfer.files);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    handleFileSelect(e.target.files);
    e.target.value = ''; // Reset input
  };

  const handleUpload = async (file: File) => {
    setIsUploading(true);
    setUploadProgress(0);

    try {
      await onUpload(file, (progress) => {
        setUploadProgress(progress);
      });
      
      setSelectedFiles(prev => prev.filter(f => f !== file));
      toast.success('Archivo subido correctamente');
    } catch (error) {
      toast.error('Error al subir el archivo');
    } finally {
      setIsUploading(false);
      setUploadProgress(0);
    }
  };

  const removeFile = (file: File) => {
    setSelectedFiles(prev => prev.filter(f => f !== file));
  };

  const clearAllFiles = () => {
    setSelectedFiles([]);
  };

  return (
    <div className="space-y-4">
      {selectedFiles.length === 0 ? (
        <div
          className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
            dragOver
              ? 'border-blue-400 bg-blue-50'
              : 'border-gray-300 hover:border-gray-400'
          }`}
          onDragOver={(e) => {
            e.preventDefault();
            setDragOver(true);
          }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
        >
          <Upload className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <p className="text-sm text-gray-600 mb-2">
            Arrastra y suelta {multiple ? 'archivos' : 'un archivo'} aquí, o 
          </p>
          <label className="inline-block">
            <input
              type="file"
              className="hidden"
              accept={accept}
              multiple={multiple}
              onChange={handleFileChange}
              disabled={loading || isUploading}
            />
            <Button
              variant="outline"
              as="span"
              className="cursor-pointer"
              disabled={loading || isUploading}
            >
              Seleccionar {multiple ? 'archivos' : 'archivo'}
            </Button>
          </label>
          <p className="text-xs text-gray-500 mt-2">
            Tipos permitidos: {accept} • Máximo {formatFileSize(maxSize)}
            {multiple && ' por archivo'}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-medium text-gray-900">
              {selectedFiles.length} archivo{selectedFiles.length > 1 ? 's' : ''} seleccionado{selectedFiles.length > 1 ? 's' : ''}
            </h4>
            {selectedFiles.length > 1 && (
              <Button
                variant="outline"
                size="sm"
                onClick={clearAllFiles}
                disabled={isUploading}
              >
                Limpiar todo
              </Button>
            )}
          </div>

          {isUploading && (
            <ProgressBar progress={uploadProgress} />
          )}

          <div className="space-y-2">
            {selectedFiles.map((file, index) => (
              <div key={index} className="border border-gray-200 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <File className="h-8 w-8 text-blue-600" />
                    <div>
                      <p className="text-sm font-medium text-gray-900">
                        {file.name}
                      </p>
                      <p className="text-sm text-gray-500">
                        {formatFileSize(file.size)}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Button
                      variant="primary"
                      size="sm"
                      onClick={() => handleUpload(file)}
                      loading={isUploading}
                      disabled={loading}
                    >
                      Subir
                    </Button>
                    <button
                      onClick={() => removeFile(file)}
                      className="text-gray-400 hover:text-red-600 transition-colors"
                      disabled={isUploading || loading}
                    >
                      <X className="h-5 w-5" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="border-2 border-dashed border-gray-300 rounded-lg p-4 text-center">
            <label className="cursor-pointer">
              <input
                type="file"
                className="hidden"
                accept={accept}
                multiple={multiple}
                onChange={handleFileChange}
                disabled={loading || isUploading}
              />
              <span className="text-sm text-gray-600">
                + Agregar más archivos
              </span>
            </label>
          </div>
        </div>
      )}

      {/* Error/Warning messages */}
      <div className="text-xs text-gray-500">
        <div className="flex items-center space-x-1">
          <AlertCircle className="h-3 w-3" />
          <span>
            Los archivos se suben individualmente. Tipos permitidos: {accept}
          </span>
        </div>
      </div>
    </div>
  );
};

export default FileUploader;
