// project/src/pages/Main/Main.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { useEstadisticas } from '../../hooks/useEstadisticas';
import { FileText, Users, Scale, TrendingUp, Clock, AlertCircle, RefreshCw } from 'lucide-react';
import Button from '../../components/UI/Button';

const Main: React.FC = () => {
  const { user } = useAuth();
  const { dashboardStats, loading, refreshStats } = useEstadisticas();

  const quickActions = [
    {
      title: 'Ver Expedientes',
      description: 'Administrar y consultar todos los expedientes',
      icon: FileText,
      href: '/expedientes',
      color: 'bg-blue-500',
    },
    {
      title: 'Registrar Usuario',
      description: 'Crear nuevos usuarios del sistema',
      icon: Users,
      href: '/usuarios/registrar',
      color: 'bg-green-500',
    },
  ];

  const stats = [
    {
      name: 'Expedientes Activos',
      value: loading ? '...' : dashboardStats.expedientesActivos.toString(),
      icon: Scale,
      color: 'text-blue-600',
      bgColor: 'bg-blue-100',
    },
    {
      name: 'En Progreso',
      value: loading ? '...' : dashboardStats.enProgreso.toString(),
      icon: Clock,
      color: 'text-yellow-600',
      bgColor: 'bg-yellow-100',
    },
    {
      name: 'Finalizados',
      value: loading ? '...' : dashboardStats.finalizados.toString(),
      icon: TrendingUp,
      color: 'text-green-600',
      bgColor: 'bg-green-100',
    },
    {
      name: 'Urgentes',
      value: loading ? '...' : dashboardStats.urgentes.toString(),
      icon: AlertCircle,
      color: 'text-red-600',
      bgColor: 'bg-red-100',
    },
  ];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Panel Principal
          </h1>
          <p className="text-gray-600">
            Bienvenido, <span className="font-semibold">{user?.username}</span>. 
            Administra expedientes y gestiona el sistema jurídico.
          </p>
        </div>
        <Button
          variant="outline"
          onClick={refreshStats}
          disabled={loading}
          className="flex items-center space-x-2"
        >
          <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
          <span>Actualizar</span>
        </Button>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <div
              key={stat.name}
              className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"
            >
              <div className="flex items-center">
                <div className={`p-2 rounded-lg ${stat.bgColor}`}>
                  <Icon className={`h-6 w-6 ${stat.color}`} />
                </div>
                <div className="ml-4">
                  <p className="text-sm font-medium text-gray-600">{stat.name}</p>
                  <p className="text-2xl font-semibold text-gray-900">{stat.value}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Quick Actions */}
      <div>
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          Acciones Rápidas
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {quickActions.map((action) => {
            const Icon = action.icon;
            return (
              <Link
                key={action.title}
                to={action.href}
                className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 hover:shadow-md transition-shadow group"
              >
                <div className="flex items-start space-x-4">
                  <div className={`p-3 rounded-lg ${action.color} group-hover:scale-110 transition-transform`}>
                    <Icon className="h-6 w-6 text-white" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold text-gray-900 mb-2 group-hover:text-blue-700 transition-colors">
                      {action.title}
                    </h3>
                    <p className="text-gray-600">
                      {action.description}
                    </p>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      </div>

      {/* Recent Activity - Comentado temporalmente hasta implementar historial real */}
      {/* 
      <div>
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          Actividad Reciente
        </h2>
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 divide-y divide-gray-200">
          <div className="p-4 text-center text-gray-500">
            No hay actividad reciente registrada
          </div>
        </div>
      </div>
      */}
    </div>
  );
};

export default Main;

// backend-laravel/resources/js/pages/Main/Main.vue
<script setup lang="ts">
import { computed, unref, type Component } from 'vue';
import { RouterLink } from 'vue-router';
import {
  AlertCircle,
  Clock,
  FileText,
  RefreshCw,
  Scale,
  TrendingUp,
  Users,
} from '@lucide/vue';
import { useAuth } from '@/composables/useAuth';
import { useEstadisticas } from '@/composables/useEstadisticas';
import Button from '@/components/UI/Button.vue';

interface QuickAction {
  title: string;
  description: string;
  icon: Component;
  href: string;
  color: string;
}

const auth = useAuth();
const user = computed(() => unref(auth.user));
const isAdmin = computed(() => unref(auth.isAdmin));
const { dashboardStats, loading, refreshStats } = useEstadisticas();

const allQuickActions: Array<QuickAction & { adminOnly?: boolean }> = [
  {
    title: 'Ver Expedientes',
    description: 'Administrar y consultar todos los expedientes',
    icon: FileText,
    href: '/expedientes',
    color: 'bg-blue-500',
  },
  {
    title: 'Registrar Usuario',
    description: 'Crear nuevos usuarios del sistema',
    icon: Users,
    href: '/usuarios/registrar',
    color: 'bg-green-500',
    adminOnly: true,
  },
];

const quickActions = computed(() =>
  allQuickActions.filter((action) => !action.adminOnly || isAdmin.value),
);

const stats = computed(() => [
  {
    name: 'Expedientes Activos',
    value: loading.value ? '...' : String(dashboardStats.value.expedientesActivos),
    icon: Scale,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
  },
  {
    name: 'En Progreso',
    value: loading.value ? '...' : String(dashboardStats.value.enProgreso),
    icon: Clock,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
  },
  {
    name: 'Finalizados',
    value: loading.value ? '...' : String(dashboardStats.value.finalizados),
    icon: TrendingUp,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
  },
  {
    name: 'Urgentes',
    value: loading.value ? '...' : String(dashboardStats.value.urgentes),
    icon: AlertCircle,
    color: 'text-red-600',
    bgColor: 'bg-red-100',
  },
]);

</script>

<template>
  <div class="space-y-8">
    <div class="flex items-start justify-between">
      <div>
        <h1 class="mb-2 text-3xl font-bold text-gray-900">
          Panel Principal
        </h1>
        <p class="text-gray-600">
          Bienvenido,
          <span class="font-semibold">{{ user?.username }}</span>.
          Administra expedientes y gestiona el sistema jurídico.
        </p>
      </div>
      <Button
        variant="outline"
        :disabled="loading"
        class="flex items-center space-x-2"
        @click="refreshStats"
      >
        <RefreshCw :class="['h-4 w-4', loading ? 'animate-spin' : '']" />
        <span>Actualizar</span>
      </Button>
    </div>

    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
      <div
        v-for="stat in stats"
        :key="stat.name"
        class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm"
      >
        <div class="flex items-center">
          <div :class="['rounded-lg p-2', stat.bgColor]">
            <component
              :is="stat.icon"
              :class="['h-6 w-6', stat.color]"
            />
          </div>
          <div class="ml-4">
            <p class="text-sm font-medium text-gray-600">
              {{ stat.name }}
            </p>
            <p class="text-2xl font-semibold text-gray-900">
              {{ stat.value }}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div>
      <h2 class="mb-4 text-xl font-semibold text-gray-900">
        Acciones Rápidas
      </h2>
      <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
        <RouterLink
          v-for="action in quickActions"
          :key="action.title"
          :to="action.href"
          class="group rounded-lg border border-gray-200 bg-white p-6 shadow-sm transition-shadow hover:shadow-md"
        >
          <div class="flex items-start space-x-4">
            <div
              :class="[
                'rounded-lg p-3 transition-transform group-hover:scale-110',
                action.color,
              ]"
            >
              <component
                :is="action.icon"
                class="h-6 w-6 text-white"
              />
            </div>
            <div class="flex-1">
              <h3 class="mb-2 text-lg font-semibold text-gray-900 transition-colors group-hover:text-blue-700">
                {{ action.title }}
              </h3>
              <p class="text-gray-600">
                {{ action.description }}
              </p>
            </div>
          </div>
        </RouterLink>
      </div>
    </div>
  </div>
</template>
