// backend-laravel/resources/js/pages/RegistrarUsuario/RegistrarUsuario.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Lock, User, UserCheck } from '@lucide/vue';
import { usuariosAPI } from '@/api';
import { useToast } from '@/composables/useToast';
import Button from '@/components/UI/Button.vue';

interface Rol {
  id: number;
  nombre: string;
}

interface RegistrationForm {
  nombre: string;
  username: string;
  password: string;
  confirmarPassword: string;
  rol: string;
}

interface ApiErrorPayload {
  message?: string;
  error?: string;
  errors?: Record<string, string[]>;
}

const router = useRouter();
const toast = useToast();
const loading = ref(false);
const roles = ref<Rol[]>([]);
const loadingRoles = ref(true);
const errors = ref<Record<string, string>>({});
const formData = reactive<RegistrationForm>({
  nombre: '',
  username: '',
  password: '',
  confirmarPassword: '',
  rol: 'usuario',
});

function apiErrorMessage(error: unknown, fallback: string) {
  const payload = (
    error as { response?: { data?: ApiErrorPayload }; message?: string }
  ).response?.data;
  const validationMessage = payload?.errors
    ? Object.values(payload.errors).flat()[0]
    : undefined;

  return (
    payload?.message ||
    payload?.error ||
    validationMessage ||
    (error as { message?: string }).message ||
    fallback
  );
}

function loadRoles() {
  loadingRoles.value = true;

  try {
    // Son los roles definidos por los seeders y las validaciones de Laravel.
    roles.value = [
      { id: 1, nombre: 'ADMIN' },
      { id: 2, nombre: 'USUARIO' },
    ];
    formData.rol = 'USUARIO';
  } catch (error) {
    console.error('Error al cargar roles:', error);
    toast.error('No se pudieron cargar los roles disponibles');
  } finally {
    loadingRoles.value = false;
  }
}

function validateForm() {
  const nextErrors: Record<string, string> = {};

  if (!formData.nombre.trim()) {
    nextErrors.nombre = 'El nombre completo es obligatorio';
  }

  if (!formData.username.trim()) {
    nextErrors.username = 'El usuario es obligatorio';
  } else if (formData.username.length < 3) {
    nextErrors.username = 'El usuario debe tener al menos 3 caracteres';
  }

  if (!formData.password.trim()) {
    nextErrors.password = 'La contraseña es obligatoria';
  } else if (formData.password.length < 6) {
    nextErrors.password = 'La contraseña debe tener al menos 6 caracteres';
  }

  if (formData.password !== formData.confirmarPassword) {
    nextErrors.confirmarPassword = 'Las contraseñas no coinciden';
  }

  errors.value = nextErrors;
  return Object.keys(nextErrors).length === 0;
}

function clearError(field: keyof RegistrationForm) {
  if (errors.value[field]) {
    errors.value = { ...errors.value, [field]: '' };
  }
}

async function handleSubmit() {
  if (!validateForm()) {
    return;
  }

  loading.value = true;

  try {
    const selectedRole = roles.value.find((role) => role.nombre === formData.rol);

    await usuariosAPI.create({
      nombre: formData.nombre,
      username: formData.username,
      password: formData.password,
      rol_id: selectedRole?.id ?? 2,
    });

    toast.success('Usuario registrado correctamente');
    await router.push('/usuarios');
  } catch (error) {
    toast.error(apiErrorMessage(error, 'Error al registrar usuario'));
  } finally {
    loading.value = false;
  }
}

function displayRoleName(role: string) {
  return role.charAt(0).toUpperCase() + role.slice(1);
}

onMounted(loadRoles);
</script>

<template>
  <div class="mx-auto max-w-2xl">
    <div class="rounded-lg border border-gray-200 bg-white p-8 shadow-sm">
      <div class="mb-6">
        <h1 class="mb-2 text-2xl font-bold text-gray-900">
          Registrar Nuevo Usuario
        </h1>
        <p class="text-gray-600">
          Complete la información para crear un nuevo usuario del sistema
        </p>
      </div>

      <form
        class="space-y-6"
        @submit.prevent="handleSubmit"
      >
        <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
          <div>
            <label
              for="nombre"
              class="mb-1 block text-sm font-medium text-gray-700"
            >
              Nombre Completo *
            </label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <User class="h-5 w-5 text-gray-400" />
              </div>
              <input
                id="nombre"
                v-model="formData.nombre"
                type="text"
                name="nombre"
                :class="[
                  'block w-full rounded-md border py-2 pl-10 pr-3 shadow-sm placeholder-gray-400 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500',
                  errors.nombre ? 'border-red-500' : 'border-gray-300',
                ]"
                placeholder="Juan Pérez"
                @input="clearError('nombre')"
              />
            </div>
            <p
              v-if="errors.nombre"
              class="mt-1 text-sm text-red-600"
            >
              {{ errors.nombre }}
            </p>
          </div>

          <div>
            <label
              for="username"
              class="mb-1 block text-sm font-medium text-gray-700"
            >
              Usuario *
            </label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <User class="h-5 w-5 text-gray-400" />
              </div>
              <input
                id="username"
                v-model="formData.username"
                type="text"
                name="username"
                :class="[
                  'block w-full rounded-md border py-2 pl-10 pr-3 shadow-sm placeholder-gray-400 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500',
                  errors.username ? 'border-red-500' : 'border-gray-300',
                ]"
                placeholder="Nombre de usuario"
                @input="clearError('username')"
              />
            </div>
            <p
              v-if="errors.username"
              class="mt-1 text-sm text-red-600"
            >
              {{ errors.username }}
            </p>
          </div>

          <div>
            <label
              for="password"
              class="mb-1 block text-sm font-medium text-gray-700"
            >
              Contraseña *
            </label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <Lock class="h-5 w-5 text-gray-400" />
              </div>
              <input
                id="password"
                v-model="formData.password"
                type="password"
                name="password"
                :class="[
                  'block w-full rounded-md border py-2 pl-10 pr-3 shadow-sm placeholder-gray-400 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500',
                  errors.password ? 'border-red-500' : 'border-gray-300',
                ]"
                placeholder="Mínimo 6 caracteres"
                @input="clearError('password')"
              />
            </div>
            <p
              v-if="errors.password"
              class="mt-1 text-sm text-red-600"
            >
              {{ errors.password }}
            </p>
          </div>

          <div>
            <label
              for="confirmarPassword"
              class="mb-1 block text-sm font-medium text-gray-700"
            >
              Confirmar Contraseña *
            </label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <Lock class="h-5 w-5 text-gray-400" />
              </div>
              <input
                id="confirmarPassword"
                v-model="formData.confirmarPassword"
                type="password"
                name="confirmarPassword"
                :class="[
                  'block w-full rounded-md border py-2 pl-10 pr-3 shadow-sm placeholder-gray-400 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500',
                  errors.confirmarPassword ? 'border-red-500' : 'border-gray-300',
                ]"
                placeholder="Repita la contraseña"
                @input="clearError('confirmarPassword')"
              />
            </div>
            <p
              v-if="errors.confirmarPassword"
              class="mt-1 text-sm text-red-600"
            >
              {{ errors.confirmarPassword }}
            </p>
          </div>
        </div>

        <div>
          <label
            for="rol"
            class="mb-1 block text-sm font-medium text-gray-700"
          >
            Rol
          </label>
          <div class="relative">
            <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <UserCheck class="h-5 w-5 text-gray-400" />
            </div>
            <select
              id="rol"
              v-model="formData.rol"
              name="rol"
              :disabled="loadingRoles"
              class="block w-full rounded-md border border-gray-300 py-2 pl-10 pr-3 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 disabled:cursor-not-allowed disabled:bg-gray-100"
            >
              <option v-if="loadingRoles">
                Cargando roles...
              </option>
              <template v-else-if="roles.length > 0">
                <option
                  v-for="rol in roles"
                  :key="rol.id"
                  :value="rol.nombre"
                >
                  {{ displayRoleName(rol.nombre) }}
                </option>
              </template>
              <option
                v-else
                value="usuario"
              >
                Usuario
              </option>
            </select>
          </div>
        </div>

        <div class="flex justify-end space-x-4 border-t border-gray-200 pt-6">
          <Button
            type="button"
            variant="outline"
            @click="router.push('/main')"
          >
            Cancelar
          </Button>
          <Button
            type="submit"
            variant="primary"
            :loading="loading"
          >
            Registrar Usuario
          </Button>
        </div>
      </form>
    </div>
  </div>
</template>

// project/src/pages/RegistrarUsuario/RegistrarUsuario.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { usuariosAPI } from '../../api';
import { User, Lock, UserCheck } from 'lucide-react';
import Button from '../../components/UI/Button';
import toast from 'react-hot-toast';

interface Rol {
  id: number;
  nombre: string;
}

const RegistrarUsuario: React.FC = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [roles, setRoles] = useState<Rol[]>([]);
  const [loadingRoles, setLoadingRoles] = useState(true);
  const [formData, setFormData] = useState({
    nombre: '',
    username: '',
    password: '',
    confirmarPassword: '',
    rol: 'usuario',
  });
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Cargar roles disponibles al montar el componente
  useEffect(() => {
    const fetchRoles = async () => {
      try {
        // Roles fijos basados en el backend Laravel
        const rolesData: Rol[] = [
          { id: 1, nombre: 'ADMIN' },
          { id: 2, nombre: 'USUARIO' },
        ];
        setRoles(rolesData);
        setFormData(prev => ({ ...prev, rol: 'USUARIO' }));
      } catch (error) {
        console.error('Error al cargar roles:', error);
        toast.error('No se pudieron cargar los roles disponibles');
      } finally {
        setLoadingRoles(false);
      }
    };

    fetchRoles();
  }, []);

  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    if (!formData.nombre.trim()) {
      newErrors.nombre = 'El nombre completo es obligatorio';
    }

    if (!formData.username.trim()) {
      newErrors.username = 'El usuario es obligatorio';
    } else if (formData.username.length < 3) {
      newErrors.username = 'El usuario debe tener al menos 3 caracteres';
    }

    if (!formData.password.trim()) {
      newErrors.password = 'La contraseña es obligatoria';
    } else if (formData.password.length < 6) {
      newErrors.password = 'La contraseña debe tener al menos 6 caracteres';
    }

    if (formData.password !== formData.confirmarPassword) {
      newErrors.confirmarPassword = 'Las contraseñas no coinciden';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setLoading(true);

    try {
      // Remove confirmarPassword before sending to API
      const { confirmarPassword, ...userData } = formData;
      
      // Buscar el rol_id basado en el nombre del rol
      const selectedRole = roles.find(r => r.nombre === userData.rol);
      const rol_id = selectedRole?.id || 2; // Default a usuario (2)
      
      await usuariosAPI.create({
        nombre: userData.nombre,
        username: userData.username,
        password: userData.password,
        rol_id: rol_id,
      });
      
      toast.success('Usuario registrado correctamente');
      navigate('/usuarios');
    } catch (error) {
      // Error handling is done by the API interceptor
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  return (
    <div className="max-w-2xl mx-auto">
      <div className="bg-white shadow-sm rounded-lg border border-gray-200 p-8">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">
            Registrar Nuevo Usuario
          </h1>
          <p className="text-gray-600">
            Complete la información para crear un nuevo usuario del sistema
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label htmlFor="nombre" className="block text-sm font-medium text-gray-700 mb-1">
                Nombre Completo *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <User className="h-5 w-5 text-gray-400" />
                </div>
                <input
                  type="text"
                  id="nombre"
                  name="nombre"
                  value={formData.nombre}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-3 py-2 border rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 ${
                    errors.nombre ? 'border-red-500' : 'border-gray-300'
                  }`}
                  placeholder="Juan Pérez"
                />
              </div>
              {errors.nombre && (
                <p className="mt-1 text-sm text-red-600">{errors.nombre}</p>
              )}
            </div>

            <div>
              <label htmlFor="username" className="block text-sm font-medium text-gray-700 mb-1">
                Usuario *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <User className="h-5 w-5 text-gray-400" />
                </div>
                <input
                  type="text"
                  id="username"
                  name="username"
                  value={formData.username}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-3 py-2 border rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 ${
                    errors.username ? 'border-red-500' : 'border-gray-300'
                  }`}
                  placeholder="Nombre de usuario"
                />
              </div>
              {errors.username && (
                <p className="mt-1 text-sm text-red-600">{errors.username}</p>
              )}
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
                Contraseña *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Lock className="h-5 w-5 text-gray-400" />
                </div>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={formData.password}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-3 py-2 border rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 ${
                    errors.password ? 'border-red-500' : 'border-gray-300'
                  }`}
                  placeholder="Mínimo 6 caracteres"
                />
              </div>
              {errors.password && (
                <p className="mt-1 text-sm text-red-600">{errors.password}</p>
              )}
            </div>

            <div>
              <label htmlFor="confirmarPassword" className="block text-sm font-medium text-gray-700 mb-1">
                Confirmar Contraseña *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <Lock className="h-5 w-5 text-gray-400" />
                </div>
                <input
                  type="password"
                  id="confirmarPassword"
                  name="confirmarPassword"
                  value={formData.confirmarPassword}
                  onChange={handleChange}
                  className={`block w-full pl-10 pr-3 py-2 border rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 ${
                    errors.confirmarPassword ? 'border-red-500' : 'border-gray-300'
                  }`}
                  placeholder="Repita la contraseña"
                />
              </div>
              {errors.confirmarPassword && (
                <p className="mt-1 text-sm text-red-600">{errors.confirmarPassword}</p>
              )}
            </div>
          </div>

          <div>
            <label htmlFor="rol" className="block text-sm font-medium text-gray-700 mb-1">
              Rol
            </label>
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <UserCheck className="h-5 w-5 text-gray-400" />
              </div>
              <select
                id="rol"
                name="rol"
                value={formData.rol}
                onChange={handleChange}
                disabled={loadingRoles}
                className="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 disabled:bg-gray-100 disabled:cursor-not-allowed"
              >
                {loadingRoles ? (
                  <option>Cargando roles...</option>
                ) : roles.length > 0 ? (
                  roles.map((rol) => (
                    <option key={rol.id} value={rol.nombre}>
                      {rol.nombre.charAt(0).toUpperCase() + rol.nombre.slice(1)}
                    </option>
                  ))
                ) : (
                  <option value="usuario">Usuario</option>
                )}
              </select>
            </div>
          </div>

          <div className="flex justify-end space-x-4 pt-6 border-t border-gray-200">
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate('/main')}
            >
              Cancelar
            </Button>
            <Button
              type="submit"
              variant="primary"
              loading={loading}
            >
              Registrar Usuario
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default RegistrarUsuario;
