// backend-laravel/resources/js/components/UI/ProgressBar.vue
<script setup lang="ts">
import { computed } from 'vue';

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    progress: number;
    showPercentage?: boolean;
    className?: string;
  }>(),
  {
    showPercentage: true,
    className: '',
  },
);

const clampedProgress = computed(() =>
  Math.max(0, Math.min(100, Number.isFinite(props.progress) ? props.progress : 0)),
);

const roundedProgress = computed(() => Math.round(clampedProgress.value));
</script>

<template>
  <div
    v-bind="$attrs"
    :class="['w-full', props.className]"
  >
    <div class="mb-1 flex items-center justify-between">
      <span class="text-sm font-medium text-gray-700">
        Subiendo archivo...
      </span>
      <span
        v-if="props.showPercentage"
        class="text-sm font-medium text-gray-700"
      >
        {{ roundedProgress }}%
      </span>
    </div>
    <div
      class="h-2 w-full rounded-full bg-gray-200"
      role="progressbar"
      aria-label="Progreso de subida"
      aria-valuemin="0"
      aria-valuemax="100"
      :aria-valuenow="roundedProgress"
    >
      <div
        class="h-2 rounded-full bg-blue-600 transition-all duration-300"
        :style="{ width: `${clampedProgress}%` }"
      />
    </div>
  </div>
</template>

// project/src/components/UI/ProgressBar.tsx
import React from 'react';

interface ProgressBarProps {
  progress: number;
  className?: string;
  showPercentage?: boolean;
}

const ProgressBar: React.FC<ProgressBarProps> = ({ 
  progress, 
  className = '',
  showPercentage = true 
}) => {
  const clampedProgress = Math.max(0, Math.min(100, progress));

  return (
    <div className={`w-full ${className}`}>
      <div className="flex items-center justify-between mb-1">
        <span className="text-sm font-medium text-gray-700">
          Subiendo archivo...
        </span>
        {showPercentage && (
          <span className="text-sm font-medium text-gray-700">
            {Math.round(clampedProgress)}%
          </span>
        )}
      </div>
      <div className="w-full bg-gray-200 rounded-full h-2">
        <div 
          className="bg-blue-600 h-2 rounded-full transition-all duration-300"
          style={{ width: `${clampedProgress}%` }}
        />
      </div>
    </div>
  );
};

export default ProgressBar;
