// project/src/components/Layout/Layout.tsx
import React, { useState, useEffect } from 'react';
import { Outlet, Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { LogOut, Scale, FileText, Users, Home, Menu, X } from 'lucide-react';

const Layout: React.FC = () => {
  const { user, logout, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  // Redirigir a login si el usuario cierra sesión
  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/login', { replace: true });
    }
  }, [isAuthenticated, navigate]);

  const handleLogout = () => {
    logout();
    setIsMobileMenuOpen(false);
  };

  const navigation = [
    { name: 'Panel Principal', href: '/main', icon: Home },
    { name: 'Expedientes', href: '/expedientes', icon: FileText },
    { name: 'Usuarios', href: '/usuarios', icon: Users },
    { name: 'Registrar Usuario', href: '/usuarios/registrar', icon: Users },
  ];

  const isActiveRoute = (href: string) => {
    return location.pathname === href || location.pathname.startsWith(href + '/');
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-2 sm:space-x-4">
              <Scale className="h-6 w-6 sm:h-8 sm:w-8 text-blue-700 flex-shrink-0" />
              <h1 className="text-base sm:text-xl font-semibold text-gray-900 truncate">
                {import.meta.env.VITE_APP_NAME || 'Abogados Asociados'}
              </h1>
            </div>
            
            {user && (
              <div className="flex items-center space-x-2 sm:space-x-4">
                {/* User info - hidden on small screens */}
                <span className="hidden md:block text-sm text-gray-700">
                  Bienvenido, <span className="font-medium">{user.username}</span>
                </span>
                
                {/* Logout button - responsive sizing */}
                <button
                  onClick={handleLogout}
                  className="inline-flex items-center px-2 py-1.5 sm:px-3 sm:py-2 border border-transparent text-xs sm:text-sm leading-4 font-medium rounded-md text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors"
                >
                  <LogOut className="h-3 w-3 sm:h-4 sm:w-4 sm:mr-2" />
                  <span className="hidden sm:inline">Salir</span>
                </button>

                {/* Mobile menu button */}
                <button
                  onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                  className="md:hidden p-2 rounded-md text-gray-600 hover:bg-gray-100"
                >
                  {isMobileMenuOpen ? (
                    <X className="h-6 w-6" />
                  ) : (
                    <Menu className="h-6 w-6" />
                  )}
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Mobile navigation menu */}
        {user && isMobileMenuOpen && (
          <div className="md:hidden border-t border-gray-200 bg-white">
            <div className="px-2 pt-2 pb-3 space-y-1">
              {navigation.map((item) => {
                const Icon = item.icon;
                return (
                  <Link
                    key={item.name}
                    to={item.href}
                    onClick={() => setIsMobileMenuOpen(false)}
                    className={`w-full flex items-center px-3 py-2 text-base font-medium rounded-md transition-colors ${
                      isActiveRoute(item.href)
                        ? 'bg-blue-100 text-blue-700 border-l-4 border-blue-700'
                        : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'
                    }`}
                  >
                    <Icon className="h-5 w-5 mr-3" />
                    {item.name}
                  </Link>
                );
              })}
            </div>
          </div>
        )}
      </header>

      <div className="flex">
        {/* Desktop Sidebar - hidden on mobile */}
        {user && (
          <nav className="hidden md:block w-64 bg-white shadow-sm min-h-screen border-r border-gray-200">
            <div className="p-4 space-y-2">
              {navigation.map((item) => {
                const Icon = item.icon;
                return (
                  <Link
                    key={item.name}
                    to={item.href}
                    className={`w-full flex items-center px-4 py-2 text-sm font-medium rounded-md transition-colors ${
                      isActiveRoute(item.href)
                        ? 'bg-blue-100 text-blue-700 border-r-2 border-blue-700'
                        : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'
                    }`}
                  >
                    <Icon className="h-5 w-5 mr-3" />
                    {item.name}
                  </Link>
                );
              })}
            </div>
          </nav>
        )}

        {/* Main content */}
        <main className="flex-1">
          <div className="p-4 sm:p-6">
            <Outlet />
          </div>
        </main>
      </div>
    </div>
  );
};

export default Layout;

// backend-laravel/resources/js/components/Layout/Layout.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { RouterLink, RouterView, useRoute, useRouter } from 'vue-router';
import { FileText, Home, LogOut, Menu, Scale, Users, X } from '@lucide/vue';
import { authAPI } from '@/api';
import { useAuth } from '@/composables/useAuth';

const route = useRoute();
const router = useRouter();
const { user, isAuthenticated, isAdmin, logout } = useAuth();
const isMobileMenuOpen = ref(false);
const appName = import.meta.env.VITE_APP_NAME || 'Abogados Asociados';

const navigation = computed(() => [
  { name: 'Panel Principal', href: '/main', icon: Home, adminOnly: false },
  { name: 'Expedientes', href: '/expedientes', icon: FileText, adminOnly: false },
  { name: 'Usuarios', href: '/usuarios', icon: Users, adminOnly: true },
  { name: 'Registrar Usuario', href: '/usuarios/registrar', icon: Users, adminOnly: true },
].filter((item) => !item.adminOnly || isAdmin.value));

const isActiveRoute = (href: string) => (
  route.path === href || route.path.startsWith(`${href}/`)
);

const handleLogout = async () => {
  try {
    await authAPI.logout();
  } catch (error) {
    console.warn('No se pudo invalidar el token en el servidor.', error);
  } finally {
    logout();
    isMobileMenuOpen.value = false;
    await router.replace('/login');
  }
};

watch(
  () => route.path,
  () => {
    isMobileMenuOpen.value = false;
  },
);

watch(isAuthenticated, (authenticated) => {
  if (!authenticated && route.name !== 'login') {
    void router.replace('/login');
  }
});
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <header class="border-b border-gray-200 bg-white shadow-sm">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-16 items-center justify-between">
          <div class="flex min-w-0 items-center space-x-2 sm:space-x-4">
            <Scale class="h-6 w-6 flex-shrink-0 text-blue-700 sm:h-8 sm:w-8" />
            <h1 class="truncate text-base font-semibold text-gray-900 sm:text-xl">
              {{ appName }}
            </h1>
          </div>

          <div v-if="user" class="flex items-center space-x-2 sm:space-x-4">
            <span class="hidden text-sm text-gray-700 md:block">
              Bienvenido, <span class="font-medium">{{ user.username }}</span>
            </span>

            <button
              type="button"
              class="inline-flex items-center rounded-md border border-transparent bg-blue-700 px-2 py-1.5 text-xs font-medium leading-4 text-white transition-colors hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 sm:px-3 sm:py-2 sm:text-sm"
              @click="handleLogout"
            >
              <LogOut class="h-3 w-3 sm:mr-2 sm:h-4 sm:w-4" />
              <span class="hidden sm:inline">Salir</span>
            </button>

            <button
              type="button"
              class="rounded-md p-2 text-gray-600 hover:bg-gray-100 md:hidden"
              :aria-expanded="isMobileMenuOpen"
              aria-controls="mobile-navigation"
              aria-label="Abrir menú de navegación"
              @click="isMobileMenuOpen = !isMobileMenuOpen"
            >
              <X v-if="isMobileMenuOpen" class="h-6 w-6" />
              <Menu v-else class="h-6 w-6" />
            </button>
          </div>
        </div>
      </div>

      <div
        v-if="user && isMobileMenuOpen"
        id="mobile-navigation"
        class="border-t border-gray-200 bg-white md:hidden"
      >
        <nav class="space-y-1 px-2 pb-3 pt-2" aria-label="Navegación móvil">
          <RouterLink
            v-for="item in navigation"
            :key="item.name"
            :to="item.href"
            class="flex w-full items-center rounded-md px-3 py-2 text-base font-medium transition-colors"
            :class="isActiveRoute(item.href)
              ? 'border-l-4 border-blue-700 bg-blue-100 text-blue-700'
              : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'"
          >
            <component :is="item.icon" class="mr-3 h-5 w-5" />
            {{ item.name }}
          </RouterLink>
        </nav>
      </div>
    </header>

    <div class="flex">
      <nav
        v-if="user"
        class="hidden min-h-screen w-64 border-r border-gray-200 bg-white shadow-sm md:block"
        aria-label="Navegación principal"
      >
        <div class="space-y-2 p-4">
          <RouterLink
            v-for="item in navigation"
            :key="item.name"
            :to="item.href"
            class="flex w-full items-center rounded-md px-4 py-2 text-sm font-medium transition-colors"
            :class="isActiveRoute(item.href)
              ? 'border-r-2 border-blue-700 bg-blue-100 text-blue-700'
              : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900'"
          >
            <component :is="item.icon" class="mr-3 h-5 w-5" />
            {{ item.name }}
          </RouterLink>
        </div>
      </nav>

      <main class="min-w-0 flex-1">
        <div class="p-4 sm:p-6">
          <RouterView />
        </div>
      </main>
    </div>
  </div>
</template>
